version: 2.1

jobs:
  Deploy:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: |
            yarn install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Creating new Build
          command: |
            CI=false yarn build
      - run:
          command: |
            pip install awscli
      - run:
          name: Copy Static Files
          command: aws s3 sync build/ s3://${AWS_STORAGE_BUCKET_NAME}/${CIRCLE_BRANCH}/ --acl public-read --size-only

workflows:
  build-and-deploy-branch:
    jobs:
      - Deploy
          # context: sa-addin-staging
          # filters:
          #   branches:
          #     only: master 
