version: 2.1

jobs:
  Deploy:
    docker:
      - image: circleci/python:3.8-node
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: |
            yarn install
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
            - yar
      - run:
          name: Creating new Build
          command: |
            CI=false yarn run build-demo
      - run:
          name: Run Linting
          command: |
            yarn lint
      - run:
          name: Run Tests
          command: |
            yarn test
      - run:
          command: |
            pip install awscli
      - run:
          name: Remove Existing Build
          command: aws s3 rm --recursive --endpoint=${DO_ENDPOINT} s3://${DO_SPACE}/${CIRCLE_BRANCH}/ 
      - run:
          name: Copy Static Files
          command: aws s3 cp --recursive --endpoint=${DO_ENDPOINT} build/ s3://${DO_SPACE}/${CIRCLE_BRANCH}/ --acl public-read 

workflows:
  build-and-deploy-branch:
    jobs:
      - Deploy:
          context: do-deployment
          # filters:
          #   branches:
          #     only: master 
